vtk_module(vtkFiltersParallel
  GROUPS
    StandAlone
  DEPENDS
    vtkParallelCore
    vtkFiltersExtraction
    vtkRenderingCore
    vtkFiltersModeling
    vtkFiltersGeometry
vtkImagingStatistics
  TEST_DEPENDS
    vtkParallelMPI
    vtkTestingRendering
    vtkInteractionStyle
    vtkRenderingOpenGL
    vtkRenderingParallel
    vtkFiltersParallelMPI
    vtkFiltersParallelImaging
    vtkIOLegacy
  )
